# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'TODAY I LEARNED'
tagline:             "by vàithằngnhốnhăng"
description:         ''
url:                 # http://lanyon.getpoole.com
baseurl:             '/til'
paginate:            100
permalink: /:title/

# About/contact
author:
  name:              1thằngnhốnhăng
  url:               # https://twitter.com/mdo
  email:             # markdotto@gmail.com

# Custom vars
version:             1.0.0
